apiVersion: v1
kind: Service
metadata:
  name: samplecore-service
  labels:
    app: samplecore-service
    # dns: route53
  annotations:
    # domainName: "samplecore-service.boranpoc.com"
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-1:659153740712:certificate/xxxxxxxx"
    # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  selector:
    app: samplecore
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
